### ISSUE TITLE
parse transfer market

### ISSUE THREAD

**Issue by StegSchreck** [WiSchLabs/ofm_helper#19]
the transfer market parsing should be user-independent.
resulting data shall only be visible for logged-in users

**Comment by Sh4kE** [comment]
this is resource demanding, we should really do the mysql database first

**Comment by StegSchreck** [comment]
ofm is limiting the transfer market queries by result count. so we have to do multiple requests to get the complete listing in the end

**Comment by Sh4kE** [comment]
We could try to use [b3](https://github.com/d3/d3/wiki/Gallery) for showing animated plots. Like the box plots you can find in the link

**Comment by Sh4kE** [comment]
Or we might also be able to use highcharts again if we output our dataframe as json

**Comment by Sh4kE** [comment]
[here](https://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/plotoptions/box-plot-styling/) is an example of how the data must be structered for highcharts boxplots
