### ISSUE TITLE
parse league statistics (games)

### ISSUE THREAD

**Issue by Sh4kE** [WiSchLabs/ofm_helper#47]

**Comment by Sh4kE** [comment]
unfortunatly it does not work on my machine :(

views.py:147
link_to_match = row.find_all('img')[0].find_parent('a')['href']

KeyError: 'href'

**Comment by Sh4kE** [comment]
the parent a tag has this structure:

row.find_all('img')[0].find_parent('a')
<a onmouseover="Tip('&lt;img src=/db/images/trikots/29/41/sp100px62941.png height=100px&gt;',BGCOLOR,'white',WIDTH,70,FADEIN,200,FADEOUT,200,BORDERWIDTH,1,ABOVE,true,OFFSETY,-25)"><img border="0" height="25px" src="/db/images/trikots/29/41/sp25px62941.png"/></a>

**Comment by StegSchreck** [comment]
I can't see the attached image. let's debug together

**Comment by Sh4kE** [comment]
It is not an attached image :D it is the parents a tag for debugging, only github renders that html. I didn't know how to tell github to treat it as code

**Comment by StegSchreck** [comment]
https://github.com/WiSchLabs/ofm_helper/commit/d601e557489b17811e007a405ae890e83e687666

try again
