### ISSUE TITLE
refactor out html logic into js

### ISSUE THREAD

**Issue by Sh4kE** [WiSchLabs/ofm_helper#57]

**Comment by StegSchreck** [comment]
diff view is not working correctly anymore.
initial diff is working, but not if you select a different matchday to compare to. tried with player statistics and finances

**Comment by StegSchreck** [comment]
fix found, pls review: https://github.com/WiSchLabs/ofm_helper/commit/e42768d8de579cfa9fecb769e542adc89c26778e
