### ISSUE TITLE
filter for stadium stand levels in stadium statistics

### ISSUE THREAD

**Issue by Sh4kE** [WiSchLabs/ofm_helper#61]

**Comment by StegSchreck** [comment]
what value(s) do you want to filter for?

**Comment by StegSchreck** [comment]
we want to filter for unique combinations of the stadium configuration (consisting of: north stand capacity, south stand capacity, parking level, screen level, etc.)

**Comment by Sh4kE** [comment]
We can't have that much logic in our html. That needs to be shifted to python or javascript
