### ISSUE TITLE
On my prod environment my (sold) player gets listed nine times

### ISSUE THREAD

**Issue by Sh4kE** [WiSchLabs/ofm_helper#77]
The player is only shown on matchday zero somehow. Every other matchday he does not show up.

I don't know how to reproduce it right now. It might be due to parsing errors in the past.

**Comment by Sh4kE** [comment]
[sold player shown multiple times](http://imgur.com/o0VzR80)

**Comment by StegSchreck** [comment]
please copy database for analysis next time this happens

**Comment by StegSchreck** [comment]
didn't happen to me today...
