### ISSUE TITLE
migrate to Django 1.10

### ISSUE THREAD

**Issue by Sh4kE** [WiSchLabs/ofm_helper#88]

**Comment by Sh4kE** [comment]
Why did you reopen this ticket? You already done this in the other story so nothing can be done here

**Comment by StegSchreck** [comment]
I had an open question, but i posted it in the commit, not here. Was this already all blocking django 1.10? 

we are bad in writing things (like UACs) down by the way.

**Comment by Sh4kE** [comment]
Yep that should be everything. Chartit called some functions, which have been removed in django 1.10. Our code is able to be upgraded.

**Comment by StegSchreck** [comment]
next time we should write those things down...
