### ISSUE TITLE
404 error after session expired

### ISSUE THREAD

**Issue by StegSchreck** [WiSchLabs/ofm_helper#90]
http://127.0.0.1:8000/accounts/login/?next=/ofm/matches leads to 404 error page

http://imgur.com/a/yGPTT

**Comment by Sh4kE** [comment]
It must have somthing to do with these variables:
LOGIN_REDIRECT_URL = "users:redirect"
LOGIN_URL = "login"

They can be set in the settings as well. Havent tried it yet though

**Comment by Sh4kE** [comment]
This might already be fixed, since I added these options. I don't know how to reproduce it.

**Comment by StegSchreck** [comment]
I had the problem, when I was exchanging the underlying database (for development purposes). Doesn't occur to me anymore now.
